### ISSUE TITLE
Question about different smpl_meshes used for upper and lower clothes reconstruction

### ISSUE THREAD

**Issue by WongChen** [enriccorona/SMPLicit#5]
I noticed  SMPLicit uses a atart_posed SMPL to compute points distance for pants and skirts, but uses unposed SMPL for upper clothes. Is there any reason to do so?

**Comment by WongChen** [comment]
> I noticed SMPLicit uses a atart_posed SMPL to compute points distance for pants and skirts, but uses unposed SMPL for upper clothes. Is there any reason to do so?

Is that because the pose-dependent shape deformations mainly infect lower body?

**Comment by enriccorona** [comment]
Hi, that's because in the t-posed human model, the legs are quite close. So we model the lower-body clothes (pants and skirts) with the legs a bit more open.
Otherwise the pant legs were sometimes reconstructed as a single leg after marching cubes. Also this helps for finding better correspondance to the SMPL body when re-posing the clothes.

**Comment by WongChen** [comment]
> Hi, that's because in the t-posed human model, the legs are quite close. So we model the lower-body clothes (pants and skirts) with the legs a bit more open.
> Otherwise the pant legs were sometimes reconstructed as a single leg after marching cubes. Also this helps for finding better correspondance to the SMPL body when re-posing the clothes.

Thanks for the reply. Closed this issue.
