### ISSUE TITLE
Question about Skirt

### ISSUE THREAD

**Issue by cassiePython** [enriccorona/SMPLicit#8]
Thx for your great work! When I try to fit a human, the result about the skirt is not good? Can you give me some advice?

**Comment by cassiePython** [comment]
![image](https://user-images.githubusercontent.com/15982113/121986755-b1339380-cdc9-11eb-8bb5-60ec0e368841.png)
![image](https://user-images.githubusercontent.com/15982113/121986778-be508280-cdc9-11eb-90a1-77ba001085da.png)

**Comment by enriccorona** [comment]
Hi, 
The main problem with the skirt prediction is that our training skirts were very tight to the body, so SMPLicit can't represent this skirt or others that have more volume.
It should be able to fit a longer skirt if the cloth segmentation is fine though.

We're working to improve the model, but the person in the photo is quite challenging and the SMPL prediction also is quite badly aligned to the image.

**Comment by cassiePython** [comment]
Thanks very much! Looking forward to your improvement.

**Comment by woo1** [comment]
@cassiePython 
Can you help me how to get the segmentation image?
[RP-R-CNN](https://github.com/soeaver/RP-R-CNN) Project is not available because of installation problem.
When I use the result images of [Self-Correction-Parsing](https://github.com/PeikeLi/Self-Correction-Human-Parsing), SMPLicit don't find any clothes.
Is it because of dataset difference or something different?
How can I make the cloth_segmentation images correctly?
Please help me.
